## Übungsaufgaben {-}

### Aufgabe 1

Teilen Sie in Ihrer Kleingruppe folgende Begriffe untereinander auf:

- Variable
- Kennwert
- Wert
- Grundgesamtheit
- Stichprobe
- Untersuchungselement

Gehen Sie nun für jeden Begriff wie folgt vor:

1. Erklären Sie der Reihe nach "Ihren" Begriff den anderen Gruppenmitgliedern, gerne auch mit Beispielen.
2. Die anderen Gruppenmitglieder nehmen die Rolle von unwissenden Dritten ein und stellen bei Bedarf Nachfragen.
2. Die anderen Gruppenmitglieder geben direkt danach Feedback auf die Erklärung: 
   - Was fanden Sie gut erklärt?
   - Was fanden Sie unverständlich?
   - Was hat Ihnen gefehlt?


### Aufgabe 2

Finden Sie als Gruppe jeweils zwei Beispiele für:

- systematische Zufallsstichproben
- geschichtete Zufallsstichproben
- Klumpenstichproben

### Aufgabe 3

Bestimmen Sie das Skalenniveau der folgenden Variablen. Kennzeichnen Sie darüber hinaus, ob die Variable qualitativ, diskret oder stetig ist.

a) Lebensalter in Jahren
a) Regenmenge in mm
a) Güteklasse
a) Passagieraufkommen
a) Baujahr
a) Geschwindigkeit in km/h
a) Sozialstatus (Unter-, Mittel und Oberschicht)
a) Temperatur in °F
a) Fläche eines Bundeslands in km²
a) Temperatur in K
a) Einwohnerzahl
a) Pegelstand
a) Staatsangehörigkeit
a) Interesse an Statistik (gering bis hoch)
a) Klausurnote
a) Bodentyp
a) Entfernung zum Stadtzentrum in km
a) Körpergröße
a) Kleidergröße (S bis XXL)
a) Monatliches Nettoeinkommen

### Aufgabe 4

Folgende Werte seien erfasst über die Lebensdauer von Klimaanlagen in Stunden [Beispieldatensatz `aircondit7` aus @r]:  

```
14 23 15 139 13 39 188 22 50 3 36 46 30 5 102 5 88 22 197 72 210 97 79 44
```

a) Erstellen Sie eine Häufigkeitstabelle. Welche Klassen wählen Sie und warum?
a) Zeichnen Sie ein Histogramm.
a) Beschreiben Sie die Verteilung.

### Aufgabe 5

Sind die folgenden Aussagen wahr oder unwahr?

a) Die Auswahl z. B. jedes 100. Merkmalsträgers nennt man „systematische Stichprobe“.
a) Eine Stichprobe kann eine Grundgesamtheit niemals völlig richtig repräsentieren, es gibt immer einen Zufallsfehler.
a) Die Größe der Stichprobe wird auch mit $N$ bezeichnet.
a) Klassengrenzen müssen so gewählt werden, dass alle Werte abgedeckt sind.
a) Je stärker die Werte der Variablen streuen, desto kleiner sollte die Stichprobe sein.
a) Variablen auf der Verhältnisskala sind immer metrisch und stetig.
a) Verhältnisskala und Intervallskala unterscheiden sich durch den natürlichen Nullpunkt.
a) Intervallskalierte Daten können immer auf die Nominalskala transformiert werden.
a) Ordinalskalierte Daten können immer auf die Intervallskala transformiert werden.
a) Eine stetige Variable ist nicht zwingend auch metrisch.
a) Im Gegensatz zu nominalskalierten Variablen lassen sich Werte von ordinalskalierten Variablen in eine sinnvolle Reihenfolge bringen.
a) Die relative Häufigkeit eines Werts ist nie größer als 100%.
a) Verfahren der deskriptiven Statistik sind immer auch univariat.
a) Klassengrenzen dürfen sich in Ausnahmefällen überlappen.
a) $x_3$ ist immer kleiner als $x_4$.
a) Variablen auf der Verhältnisskala haben einen natürlichen Nullpunkt.
a) Die absolute Häufigkeit eines Werts ist immer eine positive ganze Zahl.
a) Wenn man die Urliste ordnet, erhält man die geordnete Liste.
