#!/usr/bin/env Rscript

bookdown::clean_book(clean = getOption("bookdown.clean_book", FALSE))
bookdown::render_book("index.Rmd", "bookdown::gitbook")
bookdown::render_book("index.Rmd", "bookdown::pdf_book")
